---
title: "Attach Climate Data"
author: "WHMackenzie"
date: "2024-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#libraries----
library(climr)
library(tidyverse)
library(terra)
library(data.table)
source("_functions/_add_vars.R")
source("_functions/_add_vars_climr.R")
require(ClimateNAr)
require(tictoc)
```

## Call climr and attach climate data to plot data

```{r}
# BGC_5km_grid <- fread("./clean_data/WNA_BGCv12_TrainingPts_5km.csv") %>% as_tibble()
# my_points <- BGC_5km_grid %>% select(xcoord, ycoord, WNA_DEM_4326_clipped, fid) %>%
#   rename(lon = xcoord,   lat = ycoord, 
#   elev = WNA_DEM_4326_clipped, id = fid) %>% na.omit() #remove NAs
BGC_5km_grid <- fread("./clean_data/WNA_v13_50-200filtpts_15Nov.csv") %>% as_tibble()
my_points <- BGC_5km_grid %>% select(lat, lon, elev,V1) %>%
  rename(id = V1) %>% na.omit() #remove NAs

tic()
#cache_clear()
clim_dat <- downscale(
  xyz = my_points, which_refmap = "auto", 
 vars=list_vars())
toc()
clim_dat2 <- addVarsclimr(clim_dat)

#merge back with plot data 
grid.dat<-left_join(BGC_5km_grid, rename(clim_dat2, V1=id)) %>% mutate(zone = str_extract(BGC, "([A-Z]+)")) %>% select(zone, everything())
fwrite(grid.dat, "./clean_data/climr_WNAv13_trainingdat.csv")


```


```{r}
grid.samp <- grid.dat  %>% slice_sample(by = BGC, n=10) 
grid.samp2 <- grid.samp %>% select(lat, lon, elev,V1) %>% rename(id = V1) 
grid.samp <- grid.samp  %>% select(V1, BGC) %>% rename(id = V1)# %>% na.omit()
ds_out <- downscale(
  xyz = grid.samp2,
  which_refmap = "auto",
  #obs_periods = "2001_2020",
  gcm_periods = c("2041_2060", "2081_2100"),
  gcms = "ACCESS-ESM1-5",
  ssps = "ssp245",
  max_run = 2,
  return_refperiod = TRUE, ## to return the 1961-1990 normals period
  vars = c("MSP", "Tave_sm", "CMD", "Tmin_wt")
)

bgc.info <- fread("./clean_data/WNA_BGCs_Info_v13_1.csv")
grid.samp3 <-left_join(grid.samp, ds_out) %>% mutate(zone = str_extract(BGC, "([A-Z]+)")) %>%
  left_join(bgc.info) %>% filter(is.na(RUN) | RUN == "ensembleMean")

outprov <- grid.samp3 %>% filter(DataSet %in% c("USA", "AB")) %>% filter(PERIOD == "1961_1990")
grid.samp3 <- grid.samp3 %>% filter(!DataSet %in% c("USA", "AB"))
grid.samp4 <- rbind(grid.samp3, outprov) %>% select(BGC, PERIOD, MSP, Tave_sm, CMD, Tmin_wt)

fwrite(grid.samp4, "./clean_data/climate_space_test.csv")
list_gcms()



# Load the data from the CSV file
```


```{r}
library(ggplot2)
library(readr)
library(ggforce)
data <- read_csv("./clean_data/climate_space_test.csv")

# Create a scatter plot with different symbols and colors for different PERIODs
data$PERIOD <- factor(data$PERIOD, levels = c("1961_1990", "2041_2060", "2081_2100"))
data <- data[order(data$PERIOD == "1961_1990", decreasing = FALSE), ]
ggplot(data, aes(x = CMD, y = Tave_sm, color = PERIOD, shape = PERIOD)) +
  geom_point(size = 3) +
  geom_mark_hull(aes(fill = PERIOD), alpha = 0.2) +
  labs(title = "Scatter plot of MSP vs Tave_sm with different symbols and colors for different PERIODs",
       x = "CMD",
       y = "Tave_sm") +
  theme_minimal() +
  theme(legend.title = element_text(size = 10),
        legend.text = element_text(size = 8))


ggplot(data, aes(x = MSP, y = Tave_sm, color = PERIOD, shape = PERIOD)) +
  geom_point(size = 3) +
  geom_mark_hull(aes(fill = PERIOD), alpha = 0.2) +
  labs(title = "Scatter plot of MSP vs Tave_sm with different symbols and colors for different PERIODs",
       x = "MSP",
       y = "Tave_sm") +
  theme_minimal() +
  theme(legend.title = element_text(size = 10),
        legend.text = element_text(size = 8))

ggplot(data, aes(x = Tmin_wt, y = Tave_sm, color = PERIOD, shape = PERIOD)) +
  geom_point(size = 3) +
  geom_mark_hull(aes(fill = PERIOD), alpha = 0.2) +
  labs(title = "Scatter plot of MSP vs Tave_sm with different symbols and colors for different PERIODs",
       x = "Tmin_wt",
       y = "Tave_sm") +
  theme_minimal() +
  theme(legend.title = element_text(size = 10),
        legend.text = element_text(size = 8))
```


```{r climate summaries}
require(summarytools)
require(DBI)
var.list <- c("elev", "MAP", "MSP", "PAS", "MAT", "MWMT", "MCMT", "DDsub0", "DD5", "NFFD", "FFP", "EMT", "EXT", "CMD")

climate.sum <- grid.dat %>% drop_na() %>% group_by(BGC) %>% summarise(across(all_of(var.list), list(mean = mean, sd = sd, min = min, max = max)))
source("./_functions/_combined_su.R")
db <- "D:/BC_Correlation2_Vpro_2023/CoastGuide_Forested.accdb"
su <- combined_su(db)
su.nf <- su %>%
  filter(grepl('_[[:alpha:]]', SiteUnit)) %>% select(-SiteUnit.orig) %>% arrange(SiteUnit)
su <- su %>%
  filter(!grepl('support|poor|low|[$]|add|nudum|_[[:alpha:]]|X|omit|support', SiteUnit)) %>% select(-SiteUnit.orig) %>% arrange(SiteUnit)
#   filter(grepl('01', SiteUnit)) ###zonal specific
su2 <- su %>%
filter(!bgc %in% c('CWHvh3', 'CWHwh1', 'CWHwh2', 'CWHvh3', 'MHwh'))
LMH77 <- su2 %>% distinct(bgc) %>% pull(bgc)

coast.clim <- climate.sum %>% filter(BGC %in% LMH77)
fwrite(coast.clim, "./clean_data/climr_summary_LMH77.csv")
```


```{r cars}

 becmaster <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/BECMaster/BECMaster_fixing.accdb;")
plot.env <- dbReadTable(becmaster, "BECMaster_fixing_Env")
dbDisconnect(becmaster)

#make dataframe for extracting climate data
my_points <- plot.env  %>% select(Longitude, Latitude, Elevation, PlotNumber, ProjectID) %>%
  rename(lon = Longitude,   lat = Latitude, 
  elev = Elevation, id = PlotNumber)%>% mutate(lon = 0-lon) %>% na.omit() #remove NAs

## climr query for the historic data - only using 1961-1990 for now 
## what is the resolution/scale of these data? PRISM 800m downscaled to plot-level (accuracy of GPS points and elevation- double checks elev vals make bigger difference)
tic()
#cache_clear()
clim_dat <- downscale(
  xyz = my_points, which_refmap = "auto", 
 vars=var_names)
toc()
clim_dat2 <- addVarsclimr(clim_dat)

#merge back with plot data 
plot_dat<- rename(clim_dat2, PlotNumber=id)
fwrite(plot_dat, "./clean_data/plot_dat_climr.csv")

```

```{r}

 becmaster <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/BECMaster/BECMaster_fixing.accdb;")
plot.env <- dbReadTable(becmaster, "BECMaster_fixing_Env")
dbDisconnect(becmaster)

#make dataframe for extracting climate data
my_points <- plot.env %>% select(PlotNumber, ProjectID, Latitude, Longitude,  Elevation) %>%
  rename(lon = Longitude,   lat = Latitude, 
  elevation = Elevation, ID1 = PlotNumber, ID2 = ProjectID) %>% mutate(lon = 0-lon) %>% na.omit() 

#inputFile = 'C:/temp/test.csv' 
varList= 'YSM'  
periodList= c('Normal_1961_1990.nrm') 
outDir= "./clean_data/plot_dat_climateNA.csv"
tic()
test <- climateNAr(my_points,periodList,varList,outDir)
toc()
test <- addVars(test)
test <- test %>% na.omit()
fwrite(test, "./clean_data/plot_dat_climateNA.csv")

```
```{r}


#make dataframe for extracting climate data
my_points <- plot.env %>% select(PlotNumber, ProjectID, Latitude, Longitude,  Elevation) %>%
  rename(lon = Longitude,   lat = Latitude, 
  elevation = Elevation, ID1 = PlotNumber, ID2 = ProjectID) %>% mutate(lon = 0-lon) %>% na.omit() 

#inputFile = 'C:/temp/test.csv' 
varList= 'YSM'  
periodList= c('Normal_1961_1990.nrm') 
outDir= "./clean_data/plot_dat_climateNA.csv"
tic()
test <- climateNAr(my_points,periodList,varList,outDir)
toc()
test <- addVars(test)
test <- test %>% na.omit()
fwrite(test, "./clean_data/plot_dat_climateNA.csv")
```

