---
title: "Check Site Series for Plot Data"
author: "Will MacKenzie"
date: "13/09/2021"
output: html_document
---

```{r setup, include=FALSE}
require(data.table)
require(tidyverse)
require(dplyr)
require(data.tree)

```

## Import SU table and BECv12 site series
```{r import data}
SU.tab <- fread("./inputs/BECMster_V2020_2_SU.csv", stringsAsFactors = FALSE)
SU.tab$SiteUnit <- sub("a$|b$|c$", "", SU.tab$SiteUnit)
SS.Forest <- fread("./inputs/tblBEC_SiteSeries_v12.csv", stringsAsFactors = FALSE) %>% rename(SiteUnit = SS_Label, SS_Name = SiteSeriesLongName, Type = 'Forest-NonForest') %>% 
  dplyr::filter(Type == "Forest"| Type == "Deciduous") %>% select(SiteUnit, SS_Name)

SS.Forest$SiteUnit <- sub("a$|b$|c$", "", SS.Forest$SiteUnit)
SS.Forest <- SS.Forest %>%  distinct()
fwrite(SS.Forest, "./outputs/BECv12_Forest_SiteSeries.csv")
#newSS <- fread("./inputs/new_SiteSeries_v13.csv", stringsAsFactors = FALSE)##new units for analysis

```

## Create BECv12 SU from publication sorts
```{r read and merge original SUs from publications, message=FALSE}
read_plus <- function(flnm) {
    read_csv(flnm)# %>% 
        #mutate(filename = flnm)##include this line if source file name is desired in output
}

pub_SU <-
    list.files(path = "./published_SU/",
               pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))

pub_SU <- pub_SU  %>% distinct()
pub_SU$SiteUnit <-  sub("a$|b$|c$", "", pub_SU$SiteUnit) ##converts phases to site series
pub_SU2 <- left_join(SS.Forest, pub_SU) %>% select(PlotNumber, SiteUnit)
BECv12_noSorts <- anti_join(SS.Forest, pub_SU) ### Accepted site series not found in any sorts
fwrite(pub_SU2, "./outputs/BECv12_Forest_SU.csv")
new_SU <-     list.files(path = "./new_SU/",
               pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
fwrite(new_SU, "./outputs/BECv13_NewForest_SU.csv")
BECv13_SU <- rbind(pub_SU2, new_SU)

fwrite(BECv13_SU, "./outputs/BECv13_Forest_SU.csv")

```

## Import a Vpro hierarchy tree and covert to matrix
```{r clean hierarchy}

SUhier <- fread("./inputs/BECv12_Forests_Jan2021_Hierarchy.csv")
### add any hierarchical levels not in hierarchy table
treeToTable <- function(SUhier){
  hierLookup <- SUhier[,.(ID,Name)]
  HierClean <- SUhier[,.(ID,Parent,Name,Level)]
  roots <- HierClean$Parent[!HierClean$Parent %in% HierClean$ID]
  roots <- unique(roots[!is.na(roots)])
  if(length(roots) >= 1){
    warning("There are duplicate roots. Please check ID ", roots)
  }
  HierClean[is.na(Parent), Parent := 1]
  temp <- data.table(ID = roots,Parent = rep(1,length(roots)), Name = rep("XXX",length(roots)),Level = rep(1, length(roots)))
  HierClean <- rbind(HierClean,temp)
  
  HierClean[hierLookup, ParentName := i.Name, on = c(Parent = "ID")]
  HierClean[is.na(ParentName), ParentName := "root2"]
  HierClean <- HierClean[,.(Name,ParentName,Level)]
  HierClean$ParentName[!HierClean$ParentName %in% HierClean$Name]
  tree <- FromDataFrameNetwork(HierClean)
  wideTab <- ToDataFrameTypeCol(tree)
  wideTab <- as.data.table(wideTab)
  wideTab[,ID := 1:nrow(wideTab)]
  wideTab[,level_1 := NULL]
  tab2 <- melt(wideTab, id.vars = "ID")
  tab2 <- na.omit(tab2)
  tab2[HierClean, Level := i.Level, on = c(value = "Name")]
  dupLevels <- tab2[,.(Len = .N), by = .(ID,Level)]
  dupLevels <- dupLevels[Len > 1,]
  dups <- tab2[ID %in% dupLevels$ID,]
  setorder(dups,"ID")
  dups[,variable := NULL] ##these are the branches with duplicates
  tabOut <- dcast(tab2, ID ~ Level, value.var = "value", fun.aggregate = function(x){x[1]})
  setnames(tabOut, c("ID","Formation","Class","Order","Suborder","Alliance","Suball","Assoc","Subass","Facies", "Working", "SiteUnit"))
  tabOut[is.na(Subass), Subass := Assoc]
  tabOut[is.na(Suborder), Suborder := Order]
  tabOut[is.na(Suball), Suball := Alliance]
  return(list(table = tabOut, duplicates = dups))
}

temp <- treeToTable(SUhier)
Hier.clean <- temp$table
fwrite(Hier.clean, './outputs/BECv12_Hierarchy_Matrix.csv')

```

## Check for plots for each SU

```{r plots per SU, echo=FALSE}

BGCv13_nplots <- BECv13_SU %>% count(SiteUnit) %>% distinct()##plots per SU
BGCv13_missing <- anti_join(SS.Forest, BGCv13_nplots ) %>% select(-SS_Name) %>%  distinct()

```

```{r check SU units in hierarchy}
SU_in_Hier <- full_join(BGCv13_nplots, Hier.clean)
Hier.clean2 <- SU_in_Hier[!is.na(n),] #removes both hierarchy units without site series and site series without plots
Hier.clean2 <- Hier.clean2 %>% mutate(Formation = ifelse(is.na(Formation), "NewUnitstoPlace", Formation)) # adds unplaced units into the hierarchy under NewUnitstoPlace Formation
Hier.new <- Hier.clean2 %>% select(-n) %>% relocate(SiteUnit, .after = last_col())
fwrite(Hier.new, './outputs/BECv13_Hierarchy_Matrix.csv')
```


```{r reverse function to write hierarhcy back into Vpro format}
levelNames <- c("Formation", "Class", "Order", "Suborder", "Alliance", "Suball", 
"Assoc", "Subass", "Facies", "SiteUnit")
hierWide = Hier.new
tableToTree <- function(hierWide, levelNames){
  levelID <- data.table(Name = levelNames, Level = 1:length(levelNames))
  levs <- melt(hierWide, id.vars = "ID")
  levs[,ID := NULL]
  levs <- unique(levs)
  levs[levelID, Level := i.Level, on = c(variable = "Name")]
  levs <- levs[!is.na(value)]## this is unique names and where an unique ID number should be assigned
  hierWide[,ID := NULL]
  hierWide[,Root := "TempRoot"]
  setcolorder(hierWide,c(ncol(hierWide),1:(ncol(hierWide)-1)))
  paths <- tidyr::unite(hierWide, "pathString", na.rm = T, sep = "_")
  tr <- as.Node(paths,pathDelimiter = "_")
  tr$Set(Lab = tr$Get("name"))
  tr$Set(name = 1:tr$totalCount)
  dat <- ToDataFrameNetwork(tr,"Lab",direction = "climb")
  dat <- as.data.table(dat)
  setnames(dat, old = c("from","to","Lab"), new = c("Parent","ID","Name"))
  dat[levs, Level := i.Level, on = c(Name = "value")]
  setcolorder(dat,c("ID","Name","Parent","Level"))
  return(dat)
}


testReverse <- tableToTree(hierWide = copy(Hier.new),levelNames)
fwrite(testReverse, "./outputs/CleanedHierarchy.csv")
```


### Compare BGCv12 and Hierarchy SU
```{r check for inclusion of classification units}
# Hierarchy <- fread("./inputs/AllForestHier.csv", stringsAsFactors = FALSE)
# colnames(Hierarchy )[1:12]=c("PlotNumber", "Region", "Class", "Order", "SubOrder", "Alliance", "SubAlliance", "Association", "SubAssociation", "Facies", "Working", "SiteUnit")
# #Create lowest working hierarchical units
# Hierarchy$SubAssociation <- ifelse(Hierarchy$SubAssociation == "",Hierarchy$Association,Hierarchy$SubAssociation) ##if SubAssoc blank, fill with Association
# Hierarchy$SubOrder <- ifelse(Hierarchy$SubOrder == "",Hierarchy$Order,Hierarchy$SubOrder)
# Hierarchy$SubAlliance <- ifelse(Hierarchy$SubAlliance == "",Hierarchy$Alliance,Hierarchy$SubAlliance)
# 
# write.csv(Hierarchy, "AllForestHier_filled.csv")
# 
# BGCv12inHier <- left_join(BGCv12_nplots, Hierarchy)

```
`



