---
title: "Create Vegetation Summary data"
author: "Will MacKenzie"
date: "13/09/2021"
output: html_document
---

```{r setup, include=FALSE}
require(data.table)
require(tidyverse)
require(dplyr)
require(data.tree)
source("./_functions/_TreetoTable.R")
source("./_functions/_TabletoTree.R")
```

#### Import all raw vpro tables in /raw_data folder
```{r set folders, include=FALSE}
require(DBI) #loads odbc as well
 becmaster <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/BECMaster64/BECMaster64.accdb;")

<<<<<<< HEAD:0_0_Plot_SU_Hierachy_Checks.Rmd
ENV <- dbReadTable(becmaster, "BECMaster64_Env") %>% mutate(Longitude = ifelse(Longitude<0, Longitude, 0-Longitude))
ADMIN<- dbReadTable(becmaster, "BECMaster64_Admin")
VEG <- dbReadTable(becmaster, "BECMaster64_Veg")
env.fields <- colnames(ENV)
odbc::odbcListColumns(becmaster, table = "BECMaster64_ENV")
dbDisconnect(becmaster)
=======
ENV <- dbReadTable(becmaster, "BECMaster19_Env") %>% mutate(Longitude = ifelse(Longitude<0, Longitude, 0-Longitude))
ADMIN<- dbReadTable(becmaster, "BECMaster19_Admin")
#VEG <- dbReadTable(becmaster, "BECMaster19_Veg")
env.fields <- colnames(ENV)
odbc::odbcListColumns(becmaster, table = "BECMaster19_ENV")
dbDisconnect(becmaster) 
load("./clean_data/veg_plot_data.RData")
VEG <- vegdata

>>>>>>> f1de8b1daab09f296ce7530063d2dc2a4e612f71:0_1_Create_Vegsum_Data.Rmd
```

## Import SU table and BECdb for current BGC units and site series. Look for missing units. Create complete SU 

```{r import SU tables and look for errors}
require(DBI) #loads odbc as well
correlation <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; 
DBQ=D:/BC_Correlation2_Vpro_2023/CoastGuide_Forested_01Jan2023.accdb;")
all_su <- lapply(setNames(nm = (dbListTables(correlation)%>% str_subset("_SU"))), dbReadTable, conn = correlation)
dbDisconnect(correlation)
SU <- do.call(rbind.data.frame, all_su)
SU <- SU %>% mutate(bgc = substr(SiteUnit,1,9)) %>% drop_na() %>% distinct(PlotNumber, .keep_all = TRUE) %>% 
  arrange(desc(PlotNumber))
SU2 <- SU %>% select(PlotNumber, SiteUnit)

master_su <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; 
DBQ=D:/BC_Correlation2_Vpro_2023/CoastGuide_Hierarchy.accdb;")
dbWriteTable(master_su, "All_Coast_Forest_SU",  SU2, overwrite = TRUE, batch_rows = 1)
dbDisconnect(master_su)

#%>% mutate(PlotNumber = paste0("'",PlotNumber))
#fwrite(SU, "./clean_tabs/CoastGuide_All_BGC_Forest_SU.csv")
###remove phases and seral units
SU_siteseries <- SU %>% 
  filter(!str_detect(SiteUnit, '[$]'))
phases = c("a", "b", "c")
SU_siteseries$SiteUnit <- str_replace(SU_siteseries$SiteUnit, "[abc]", "")
fwrite(SU_siteseries, "./clean_tabs/CoastGuide_All_BGC_Forest_SS.csv")

SU <- SU_siteseries
###Check that there is plot data for all
missingplots <- anti_join(SU, ENV)
plots <- right_join(SU, ENV)
### Check for duplicate plot usage
usemorethanone <- SU %>% dplyr::group_by(PlotNumber) %>% dplyr::mutate(dups = n()) %>% filter(dups >1) %>% ungroup() %>% arrange(PlotNumber)
fwrite(usemorethanone, "./outputs/Coast_Plots_Used_Morethan_Once.csv")
###Summaries by BGC and by SS
plots_bgc <- SU %>% group_by(bgc) %>% dplyr::summarise(plots = n())
plots_SS <- SU %>% group_by(SiteUnit) %>% dplyr::summarise(plots = n())
SS_count <- length(unique(SU$SiteUnit))
siteunits_toofew <- plots_SS %>% filter(plots <5) #%>% dplyr::select(- PlotNumber) %>% distinct

fwrite(siteunits_toofew, "./outputs/Coast_SiteUnits_w_lessthan5plots.csv")
```
Site unit statistics
```{r}
###some evaluative stats for  units
temp2 <- temp[,c(1,5)]
VegUnits <- unique(temp2)# number of plots per unit
numspp <- ddply(temp,~Group,summarise,sppcount=length(unique(Species))) # number of species per unit
VegUnits2 <-merge(VegUnits, numspp, by= "Group" )
numspp2<-ddply(temp[temp$Constancy > 20,],~Group,summarise,sppcount=length(unique(Species))) # number of non-accidental species per unit
VegUnits2 <-merge(VegUnits2, numspp2, by= "Group" )
constspp <-ddply(temp[temp$Constancy > 59,],~Group,summarise,sppcount=length(unique(Species))) # number of constant species per unit
VegUnits2 <-merge(VegUnits2, constspp, by= "Group" )
colnames(VegUnits2)[3:5] <- c("TotalSpp","NonrareSpp","ConstSpp")
VegUnits2$Poor <- ifelse(VegUnits2$NoPlots < 5 | VegUnits2$ConstSpp<5, "Poor", "OK")
write.csv(VegUnits2, "GrasslandsUnitSpeciesTotals.csv")
```

### Compare BGCv12 and Hierarchy SU
```{r check for inclusion of classification units}
# Hierarchy <- fread("./inputs/AllForestHier.csv", stringsAsFactors = FALSE)
# colnames(Hierarchy )[1:12]=c("PlotNumber", "Region", "Class", "Order", "SubOrder", "Alliance", "SubAlliance", "Association", "SubAssociation", "Facies", "Working", "SiteUnit")
# #Create lowest working hierarchical units
# Hierarchy$SubAssociation <- ifelse(Hierarchy$SubAssociation == "",Hierarchy$Association,Hierarchy$SubAssociation) ##if SubAssoc blank, fill with Association
# Hierarchy$SubOrder <- ifelse(Hierarchy$SubOrder == "",Hierarchy$Order,Hierarchy$SubOrder)
# Hierarchy$SubAlliance <- ifelse(Hierarchy$SubAlliance == "",Hierarchy$Alliance,Hierarchy$SubAlliance)
# 
# write.csv(Hierarchy, "AllForestHier_filled.csv")
# 
# BGCv12inHier <- left_join(BGCv12_nplots, Hierarchy)

```
`



