---
title: "Cluster of Plot Data"
author: "William H MacKenzie"
date: "18/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(reshape)
require(reshape2)
require(vegan)
require(caret)
require(tcltk)
require(randomForest)
require(Matrix)
require(labdsv)
require(gdata)
require(MASS)
require(openxlsx)
require (C50)
require(tidyr)
require(stringr)
require(rpart)
require(tree)
require(rattle)
require(rpart.plot)
require(partykit)
require(vegclust)
require(standardize)
require(dplyr)
require(tictoc)
require(plyr)
require(Hmisc)
require(ggplot2)
require(ggdendro)
require(pvclust)
require(dendextend)
require(ape)
require (dbscan)
require(factoextra)
require(fpc)
require(cluster)
require(data.table)
require(harrietr)
source("./_functions/_cov_rescale.R")
```

##Import vegetation plot data produced from 0_BEC_data_import_clean.R script

```{r cars}
vegDat2 <- fread("./clean_tabs/BECMaster_VegR_clean.csv", data.table = FALSE)
taxon.all <- fread("D:/CommonTables/SpeciesMaster/SpeciesMaster01Dec2020.csv", header = T, stringsAsFactors = F, strip.white = T) %>% filter(Codetype == "U")
SU.list <- fread("./inputs/AlpineAll_2020_SU.txt", data.table = FALSE)
#SU.list2 <- fread("./inputs/Parkland_SU.txt", data.table = FALSE)
nonvasc = c(9, 10, 11)
genera = c("Salix", "Carex")
vegDat2 <- cov_rescale(vegDat2) %>% filter(!Lifeform %in% nonvasc) %>% filter(Cover2 > .5)
salix_carex <- vegDat2 %>% filter(Species == "SALIX" | Species == "CAREX") %>% filter(Cover>9) %>% select(PlotNumber) %>% unique() ## plot with undetermined dominants to remove
vegDat2 <- left_join(SU.list, vegDat2) %>% filter (!PlotNumber %in% salix_carex$PlotNumber) %>% filter(!Species %in% genera )
veg.dat <-
  vegDat2 %>% dplyr::select(PlotNumber, Species, Cover2) %>% matrify()
```


```{r cluster and cut  }
test.data <- veg.dat# [1:30,]# %>% filter(str_detect(row.names(class.dat), "ESSFwh"))%>% as.matrix#  
# test_jac.vegan <- vegan::vegdist(test.data, method = "sorensen", binary = F) %>% as.matrix
#test_jac <- philentropy::distance(test.data, method = "jaccard")
test_jac <- proxy::dist(test.data, method="ejaccard", diag=TRUE, upper = TRUE) ## ejaccard and philentropy jaccard are real-data versions extended jaccard opr taimoto

# , use.row.names = TRUE, as.dist.obj = TRUE)
test_jac.tab <- test_jac %>% as.matrix
test_jac.list <- melt_dist(test_jac.tab) %>% as.data.table #%>% filter(dist < .25)

ss_clst <- hclust(test_jac, method = "complete")
xx <- ss_clst$height %>% as.data.frame
 assocs <- cutree( ss_clst ,h =.25)
 alliances <- cutree(ss_clst, h=.5)
 suborders <- cutree(ss_clst, h=.75) 
 orders <- cutree(ss_clst, h=.9999)
k = length(unique(assocs))
k2 <- length(unique(alliances))
k3 <- length(unique(suborders))
k4 <- length(unique(orders))
# ss_dend <- fviz_dend (ss_clst , k=k, color_labels_by_k = T, lwd = .5,
#                     rect = T, cex = .5, horiz = T) %>%    plot()
  # 
assoc_SU <- as.data.frame(assocs) %>% rownames_to_column("PlotNumber") %>% mutate(assocs = paste0("SiteUnit-", assocs)) %>% arrange(desc(PlotNumber))
newassocs <- unique(assoc_SU$assocs)
alliance_SU <- as.data.frame(alliances) %>% rownames_to_column("PlotNumber") %>% mutate(alliances = paste0("SiteUnit-", alliances))%>% arrange(desc(PlotNumber))
newalliance <- unique(alliance_SU$alliances)
suborder_SU <- as.data.frame(suborders) %>% rownames_to_column("PlotNumber") %>% mutate(suborders = paste0("SiteUnit-", suborders))%>% arrange(desc(PlotNumber))
newsuborder <- unique(suborder_SU$suborders)
order_SU <- as.data.frame(orders) %>% rownames_to_column("PlotNumber") %>% mutate(orders = paste0("SiteUnit-", orders))%>% arrange(desc(PlotNumber))
fewplots <- count(order_SU$orders) %>% filter(freq <5)# %>% select(or)
order_SU <- order_SU %>% mutate(orders = ifelse((orders %in% fewplots$x), "Unplaced", orders))
neworder <- unique(order_SU$orders)

fwrite(order_SU, "./outputs/Alpine_SU.csv")
```

```{r dendrogram}
ss_dend <- fviz_dend (ss_clst , k=k4, color_labels_by_k = T, lwd = .5,
                    rect = T, cex = .5, horiz = T) %>% plot()

```

```{r cluster and cut}
#(#left_join(names)
    #ss_clst <- hcut(test_jac1,isdiss = TRUE, hc_method = "ward.D2")#k = best.clust,, hc_metric = "sorensen"
#test.data[test.data == 0] <- NA
# a=test.data[1,] %>% janitor::remove_empty(which = "cols") %>% colnames() ; b=test.data[2,]%>% janitor::remove_empty(which = "cols")%>% colnames()
# jaccard <- function(a, b) {
#     intersection = length(intersect(a, b))
#     union = length(a) + length(b) - intersection
#     return (intersection/union)
# }
# 
# #find Jaccard Similarity between the two sets 
# jaccard(a, b)
# 
# Stats123 <- dist( test.data, method="euclidean", diag=TRUE, upper = TRUE)
# Proxy123 <- proxy::dist(test.data, method="ejaccard", diag=TRUE, upper = TRUE)
# Philentropy123 <- philentropy::distance(test.data, method="jaccard")
```
## Cluster analysis of plot data and export to csv file
```{r}
Vegchord = decostand(VegMatrix,"normalize")
dd <- dist(Vegchord)
#hc <- hclust(dd, method = "ward.D2")
flexbeta <- function (dis,beta) 
{
  alpha <- (1-beta)/2
  out <- agnes(dis,meth='flex',par.method=alpha)
  out
}
hc <- flexbeta(dd,-0.25)
hc <- as.hclust(hc)
dend <- as.dendrogram(hc)
####plots from ape package
plot(as.phylo(hc), type = "unrooted", cex = 0.5,no.margin = TRUE, lab4ut = "axial")

plot(as.phylo(hc), cex = 0.5, label.offset = 0.5)
#plot(as.phylo(hc), type = "cladogram", cex = 0.5, label.offset = 0.5)
#plot(as.phylo(hc), type = "fan")

library(cluster)
fit <- kmeans(dd, 10)
#clusplot(Vegchord, fit$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
out <- cbind(Plots, clusterNum = fit$cluster)
head(out)
write.csv(out, "./outputs/ClusterMembership.csv", row.names = FALSE)
```

```{r}
# Centroid Plot against 1st 2 discriminant functions
library(fpc)
plotcluster(dd, fit$cluster)

##Import SU table of plots desired for cluster analysis
#SUhier <- read.csv("FebHierarchyLevelSU.csv", stringsAsFactors = FALSE)
#### Reduce vegdata to those listed in SUHier

########Function to define optimal eps
dbscan::kNNdistplot(dd, k =  4)
abline(h = 0.4, lty = 2)
###compute DBSAB using two different packages
set.seed(123)
# fpc package
res.fpc <- fpc::dbscan(dd, eps = 0.4, MinPts = 4)
# dbscan package
res.db <- dbscan::dbscan(dd, 0.4, 4)
#Make sure that both version produce the same results:
  
#  all(res.fpc$cluster == res.db)

 # The result can be visualized as follow:
    
    fviz_cluster(res.fpc, dd, geom = "point")
    
    
#  dbscan(data, eps, MinPts = 5, scale = FALSE, 
#       method = c("hybrid", "raw", "dist"))
# Compute DBSCAN using fpc package
set.seed(123)
db <- fpc::dbscan(dd, eps = 0.15, MinPts = 5, method = "dist")
# Plot DBSCAN results
plot(db, dd, main = "DBSCAN", frame = FALSE)
# Print DBSCAN
print(db)
## or plot with factoextra
fviz_cluster(db, fit, stand = FALSE, frame = FALSE, geom = "point")
km.res <- kmeans(dd, 5, nstart = 25)
fviz_cluster(km.res, dd, frame = FALSE, geom = "point")
```

```{r}
# library
library(ggplot2)
library(dplyr)
library(hrbrthemes)

# Build dataset with different distributions
data <- data.frame(
  type = c( rep("variable 1", 1000), rep("variable 2", 1000) ),
  value = c( rnorm(1000), rnorm(1000, mean=4) )
)

# Represent it
p <- data %>%
  ggplot( aes(x=value, fill=type)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    theme_ipsum() +
    labs(fill="")

p
```

