---
title: "NoiseClustering to Add Plots to Classification"
author: "William H MacKenzie"
date: "18/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data}

```

#####Noise Clustering with predefined classes#######################
###Create training and testing data

```{r cars}


vegDat.chord <- decostand(SUsumMatrix[-1], "normalize") ##standardise data
vegMat <- vegDat.chord
vegMat <- cbind(SUsumMatrix[,1],vegDat.chord)

####create training and testing data sets
vegNew <- vegMat[rownames(vegMat) %in% sample(rownames(vegMat), 100, replace = FALSE),] 
vegOld <- vegMat[!(rownames(vegMat) %in% rownames(vegNew)),]
#actualClass <- vegNew[,1:2] ###siteseries to grouping lookup
#rownames(vegNew)  <- vegNew[1] ###set rownames to siteseries
k <- ncol(vegOld)
n <- nrow(vegOld)
###grouping of training set
grouping <- vegOld[1]
vegOld <- vegOld[,-(1)]
vegNew <- vegNew[,-(1)]
k <- ncol(vegOld)
n <- nrow(vegOld)

grouping <- as.vector.factor(grouping)
vegOld.clust <- as.vegclust(vegOld, grouping)###create noise clustering with grouping as classes
###Kmeans Clustering
vegOld.kmclst <- vegclust(x = vegOld[,-1], mobileCenters=5, method = "KM", nstart=20)###create noise clustering with grouping as classes
t(vegOld.kmclst$memb)
###NC Clustering
vegOld.kmclst <- vegclust(x = vegOld[,-1], mobileCenters=5, method = "NC", m=1.2, dnoise=0.8, nstart=20)###create noise clustering with grouping as classes
round(t(vegOld.kmclst$memb), dig=2)
groups = defuzzify(vegOld.kmclst, method="cut", alpha=0.8)$cluster
table(groups)


vegComb <- vegclass(vegOld.clust, vegNew) ##classify vegNew
vegComb.memb <- vegComb[["memb"]]
newGroup <- dematrify(vegComb.memb) ##extract classification
newGroup <- newGroup[,1:2]
colnames(newGroup) <- c("SiteSeries","Class")
newGroup <- cbind(newGroup, actualClass$Class)####merge actual classification for comparison
colnames(newGroup)[3] <- "Actual"

###MDS for visualisation
MDS <- metaMDS(vegNew, distance = "bray", k = 2, trymax = 200)
MDS.df <- as.data.frame(scores(MDS, display = "sites"))###extract mds scores
MDS.df$SiteSeries <- rownames(MDS.df)
MDS.df <- merge(MDS.df,newGroup, by = "SiteSeries") ##merge predicted and actual classification
MDS.df <- MDS.df[,-1]

colnames(MDS.df)[3:4] <- c("Actual","Predict")

ggplot(MDS.df)+
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, colour = Predict), size = 2.5, shape = 17)+
  coord_fixed()+
  theme_bw()+
  theme(legend.position = "none")
```

