---
title: "Build Associations for LMH77"
author: "William H MacKenzie"
date: today
format:
  typst:
    toc: false
    toc-depth: 1
    toc-title: Contents
    section-numbering: 1.1.1
    columns: 1
output-file: "MH_Generated_Hierarchy.pdf"
editor: source
execute:
  echo: false
  error: false
  warning: false
  message: false
  fig.width: 6
  fig.height: 4
  fig.align: 'center'
  fig.cap: true
  fig.pos: H
  out.width: '100%'
  dev: pdf
  fig.ext: pdf
  cache: false
  fig.retina: 2
  dpi: 600
  fig.asp: 1.5
  fig.path: "./figures/"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(tidyverse)
require(DBI)
require(data.table)
require(cluster)
require(dendextend)
require(dynamicTreeCut)
require(gtable)
require(gtsummary)
require(colorspace)
require(openxlsx)
require(tictoc)
require(labdsv)
require(indicspecies)
require(Polychrome)
require(ggdendro)
require(purrr)
require(ggplotify)
require(grid)
require(data.tree)
library(stats)
library(overlapping)
require(gt)
require(vegan)
library(tidytext)
library(stringr)

set.seed(1279)
source("../BEC_R_working/_functions/_bec_dist.R")
source("../BEC_R_working/_functions/_bec_dist_matrix.R")
source("../BEC_R_working/_functions/_combine_taxa.R")
source("../BEC_R_working/_functions/_combine_taxa_strata.R")
source("../BEC_R_working/_functions/_create_su_vegdata.R")
source("../BEC_R_working/_functions/_create_analysis_vegsum.R")
source("../BEC_R_working/_functions/_TabletoTree.R")
source("../BEC_R_working/_functions/_TreetoTable.R")
source("../BEC_R_working/_functions/_add_vars.R")
source("../BEC_R_working/_functions/_do_pairwise.R")
source("../BEC_R_working/_functions/_create_diagnostic_veg.R")
source("../BEC_R_working/_functions/_return_similar_pairs.R")
source("../BEC_R_working/_functions/_read_sppmaster.R")
source("../BEC_R_working/_functions/_combined_su.R")
source("../BEC_R_working/_functions/_create_veg_sum.R")
source('../BEC_R_working/_functions/_create_veg_sum_all.R')
source('../BEC_R_working/_functions/_build_species_ordering.R')
source('../BEC_R_working/_functions/_format_veg_table.R')
source('../BEC_R_working/_functions/_format_veg_table_strata.R')
source('../BEC_R_working/_functions/_format_veg_table_nostrata.R')
source('../BEC_R_working/_functions/_encode_veg_sum.R')
source('../BEC_R_working/_functions/_create_dendro.R')
source('../BEC_R_working/_functions/_create_dendro_all.R')
source('../BEC_R_working/_functions/_create_dendro_bybgc.R')
source('../BEC_R_working/_functions/_draw_dendro_split.R')
source('../BEC_R_working/_functions/_cluster_groups.R')
source('../BEC_R_working/_functions/_TabletoTree.R')
source('../BEC_R_working/_functions/_build_species_ordering_hier.R')
source("../BEC_R_working/_functions/_cluster_by_spp_group.R")
source("../BEC_R_working/_functions/_generate_bec_hierarchy.R")
source("../BEC_R_working/_functions/_link_su_to_hierarchy.R")
source("../BEC_R_working/_functions/_load_veg_data.R")
source("../BEC_R_working/_functions/_load_siteunits.R")
source("../BEC_R_working/_functions/_run_pairwise_similarity.R")
source("../BEC_R_working/_functions/_generate_hierarchy_units.R")
source("../BEC_R_working/_functions/_generate_review_workbooks.R")
source("../BEC_R_working/_functions/_build_bec_distance_matrix.R")
source("../BEC_R_working/_functions/_export_similar_units.R")
source("../BEC_R_working/_functions/_create_focalunit_summary_workbook.R")
source("../BEC_R_working/_functions/_create_veg_summary_workbook.R")
source("../BEC_R_working/_functions/_create_becdb_outputs.R")
source("../BEC_R_working/_functions/_calc_diagnostic_potential.R")
```


```{r}
# anal_set <- c("MH")
# compare_set <- c("CWH-HwBa", "CWH-HwBa-rich")
# compare_set = anal_set
# #,  "CWH-HwFd", "CWH-HwFd-rich", "coast-wetfor", "MH")"CWH-102",
# BEC <- generate_bec_hierarchy(
#     anal_set,
#     compare_set,
#     group_to_test = "Association",
#     veg_file = "./clean_data/Analysis_BECMaster_Veg.rds",
#     veg_combine_db = "D:/BC_Correlation2_Vpro_2023/Correlation2_Spp_Lump.accdb",
#     veg_combine_tbl = "CorrelationII_Lump",
#     becmaster_db = "D:/BECMaster/BECMaster_fixing.accdb",
#     correlation_db = "D:/BC_Correlation2_Vpro_2023/All_BC_Correlation.accdb",
#     becdb_db = "D:/OneDrive - Government of BC/BECdb_Working/BECdb_ver14_2026_v1.accdb",
#         include_usa = FALSE,
#     similarity_params = list(
#       minconstancy = 50,
#       noiseconstancy = 10,
#       minplots = 1,
#       minor = 1,
#       use.ksi = FALSE,
#       mindiff = 0.2,
#       mindd = 0.35,
#       dominant = 7
#     ),
#     same_threshold = 0.7,
#     create_review_materials = TRUE,
#     create_env_analysis = FALSE,
#     create_BECdb = TRUE,
#     out_dir = "./review_materials/"
# )


## units to find potential similar units
compare_set <- c(
  "ICH-rich"
  # "CWH-HwBa",
  # "CWH-HwBa-rich",
  #  "MH",
  # "coast-wetfor",
  # "CWH-102",
  # "CWH-HwFd",
  # "CWH-HwFd-rich"
)
## units to report on
# anal_set <- c(
#   "CWH-HwBa-rich", "CWH-HwBa"
# )
anal_set = compare_set


results <- vector("list", length(anal_set))
names(results) <- anal_set

for(i in seq_along(anal_set)) {

  anal_set <- compare_set[i]

  message("Running analysis for ", anal_set, "...")

  results[[i]] <- generate_bec_hierarchy(
    anal_set,
    compare_set,
    group_to_test = "Association",
    veg_file = "./clean_data/Analysis_BECMaster_Veg.rds",
    veg_combine_db = "D:/BC_Correlation2_Vpro_2023/Correlation2_Spp_Lump.accdb",
    veg_combine_tbl = "CorrelationII_Lump",
    becmaster_db = "D:/BECMaster/BECMaster_fixing.accdb",
    correlation_db = "D:/BC_Correlation2_Vpro_2023/All_BC_Correlation.accdb",
    becdb_db = "D:/OneDrive - Government of BC/BECdb_Working/BECdb_ver14_2026_v1.accdb",
    include_usa = FALSE,
    similarity_params = list(
      minconstancy = 50,
      noiseconstancy = 10,
      minplots = 1,
      minor = 1,
      use.ksi = FALSE,
      mindiff = 0.2,
      mindd = 0.35,
      dominant = 7
    ),
    same_threshold = 0.7,
    create_review_materials = TRUE,
    create_env_analysis = FALSE,
    create_BECdb = TRUE,
    out_dir = "./review_materials/"
  )
}
#xx <- results$`CWH-HwBa-rich`$hierarchy$cluster_table
```



```{r}

```



