
require(labdsv)
require(gdata)
require(MASS)
require(openxlsx)
require (C50)
require(tidyr)
require(stringr)
require(rpart)
require(tree)
require(rattle)
require(rpart.plot)
require(partykit)
require(vegclust)
require(standardize)
require(dplyr)
require(tictoc)
require(plyr)
require(Hmisc)
require(ggplot2)
require(ggdendro)
require(pvclust)
require(dendextend)
require(ape)
require(doParallel)
require(data.table)

WHM_SU <- fread("./inputs/CWHds1_WHM_SU.csv")
BG_SU <- fread("./inputs/CWHds1_BG_SU.csv")

compare_SU <- left_join(WHM_SU, BG_SU)
compare_SU2 <- left_join(BG_SU, WHM_SU)
fwrite(compare_SU2, "./outputs/CWHds1BG_WHM_SU.csv")
fwrite(compare_SU, "./outputs/CWHds1WHM_BG_SU.csv")
