---
title: "Create summary materials for generating formated site unit report"
author: "Will MacKenzie"
date: "13/12/2023"
output: html_document
---

```{r setup, include=FALSE}
require(data.table)
require(tidyverse)
require(dplyr)
require(data.tree)
require(DBI) #loads odbc as well
require(labdsv)
require(factoextra)
require(CooccurrenceAffinity)
require(dendextend)
require(climr)
require(terra)
require(foreach)
require(summarytools)
source("./_functions/_lump_species.R")
source("./_functions/_create_su_vegdata.R")
source("./_functions/_create_analysis_vegsum.R")
source("./_functions/_TabletoTree.R")
source("./_functions/_TreetoTable.R")
source("./_functions/_add_vars.R")
```

#### Import all analysis data and other vpro tables for building summary
```{r set folders, include=FALSE}
veg.dat <- readRDS("./clean_data/Analysis_BECMaster_Veg.rds")

 becmaster <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/GitHub/BECMaster_Cleaning/updated_vpro/BECMaster_fixing.accdb;")
plot.env <- dbReadTable(becmaster, "BECMaster_fixing_Env")
plot.admin <- dbReadTable(becmaster, "BECMaster_fixing_Admin")
dbDisconnect(becmaster)
plot.env.use <- plot.env %>% select(PlotNumber, Latitude, Longitude, MoistureRegime, NutrientRegime,  Elevation, SlopeGradient, Aspect, MesoSlopePosition, SurficialMaterialSurf, SeepageDepth, RootRestrictingDepth, RootRestrictingType, RootZoneParticleSize, SoilClassGroup, HumusForm, StrataCoverTree, StrataCoverShrub, StrataCoverHerb, StrataCoverMoss) %>% mutate(Longitude = 0-Longitude)
plot.admin.use <- plot.admin %>% select(Plot, HumusThickness, GIS_BGC, Elevation_overlay) %>% rename(PlotNumber = Plot)

# ###created in 0_0_Plot_su_Hierarchy checks script
# master_su <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; 
# DBQ=D:/BC_Correlation2_Vpro_2023/CoastGuide_Hierarchy.accdb;")
# su <- dbReadTable(master_su, "All_Coast_Forest_su")
# dbDisconnect(master_su)

master_su <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)};
DBQ=D:/BC_Correlation2_Vpro_2023/working/All_Skunkcabbage.accdb;")
su <- dbReadTable(master_su, "AllBGC_Skunkcabbage_SU")
hier <- dbReadTable(master_su, "AllBGC_Skunkcabbage_Hierarchy")
dbDisconnect(master_su)
hier2 <- treeToTable(hier)
hier2 <- hier2[[1]]
sppmaster <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=F:/OneDrive - Personal/OneDrive/BCSpeciesList/SpeciesTaxonomyMaster.accdb;")
taxon.all  <- dbReadTable(sppmaster, "USysAllSpecs")
dbDisconnect(sppmaster)
taxon.lifeform <- taxon.all %>% filter(Codetype == "U" |Codetype == "X") %>% dplyr::select(Code, ScientificName, EnglishName, Lifeform) %>% distinct

veglump <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/BC_Correlation2_Vpro_2023/CoastGuide_Spp_lump.accdb;")
lump <- dbReadTable(veglump, "CoastGuide2023_lump")
dbDisconnect(veglump) 

veg.dat2 <- lump_species(veg.dat, lump)
```

choose unit level and summarize

turn this into a loop to generate info for each unit

```{r build veg summary}
hier.choice = c("Assoc", "Subass") ##chooselevel
hier.work <- hier2 %>% select(SiteUnit, all_of(hier.choice)) %>% left_join(su)##1 combine SU and hierarchy
veg.sum.assoc <- create_su_vegdata(veg.dat2, hier.work, unit = "Assoc", .55) 
select.unit <- "Ws54 CwHw-Gaulsha-Lysiame_typic"
vegunit.select <- veg.sum.assoc %>% dplyr::filter(unit %in% select.unit) 
vegunit.sum<- create_analysis_vegsum(vegunit.select, importance = 0.5, constancy = 55, minplots = 5, covadj = .5)
vegunit.info <- vegunit.sum%>% select(unit, nplots) %>% distinct
vegunit.table <- left_join(vegunit.sum, taxon.lifeform, by = c("Species" = "Code")) %>% arrange(Lifeform, desc(spp_importance)) %>% 
  select(Lifeform, ScientificName, Constancy, MeanCov, EnglishName )
example.vegtab <- list(vegunit.info,vegunit.table)
saveRDS(example.vegtab, "./report_material/examplevegsum.rds" )
```

```{r build environment data}
hier.env <- left_join(hier.work, plot.admin.use) %>% left_join(plot.env.use) %>% filter(!is.na(Longitude))
##add elevation by overaly where missing
hier.env <- hier.env %>% mutate(Elevation = ifelse(is.na(Elevation), Elevation_overlay, Elevation))
### add Climr climate data
coords <- hier.env %>%  dplyr::rename(long = Longitude, lat = Latitude, elev = Elevation) %>% select(long,lat,elev,PlotNumber) %>% filter(!is.na(lat))
setcolorder(coords, c("long","lat","elev", "PlotNumber"))
#thebb <- climr::get_bb(coords)
coords <- as.data.frame(coords) %>% tidyr::drop_na()# 
 ##get bounding box based on input points
dbCon <- data_connect() 
#normal <- climr::normal_input_postgis(dbCon = dbCon, normal = "normal_na", bbox = thebb, cache = TRUE) ##connect to database
vars_needed <- c("DD5","SHM", "AHM", "CMD" ,"NFFD", "PAS", 
                 "EMT", "MWMT", "DD18", "bFFP", 'MCMT', 'MSP', 'MAT', 'MAP', "PPT_at", "PPT_wt", "DD_0_at", "DD_0_wt", "CMI")
require(tictoc)
tic()
climate <- climr_downscale(
  coords,
  which_normal = "BC",
  return_normal = TRUE,
  vars = vars_needed)
toc()
climate <- addVars(climate) %>% rename(PlotNumber = ID)

climate <- left_join(hier.env,climate)

climate.dat <- climate %>% dplyr::select(PlotNumber, MWMT, MCMT, MSP, AHM, SHM, DD5, PAS,MAT, MAP, DD_delayed, CMD.total) 
hier.env <- left_join(hier.env, climate.dat)

```


```{r Edatopic position}
### adjust CMD by rSMR correction factor
hier.env2 <- hier.env %>% mutate(CMD.site = ifelse(MoistureRegime == "0", CMD.total+400,
                      ifelse(MoistureRegime == "1", CMD.total+300,        
                          ifelse(MoistureRegime == "2", CMD.total+200,        
                              ifelse(MoistureRegime == "3", CMD.total+100, 
                                  ifelse(MoistureRegime == "5", CMD.total/2,
                                        ifelse(MoistureRegime == "6", CMD.total/4,
                                            ifelse(MoistureRegime == "7", CMD.total/8,
                                                  ifelse(MoistureRegime == "8", CMD.total/16, CMD.total)))))))))
SMR4 = c("0", "1", "2", "3", "4")
SMR5 = c("5")
SMR6 = c("6", "5-6", "6-7")
SMR7 = c("7", "7-", "8")
breaks4 = c(-Inf,1,200,300,400,500,600,700,800,900,1000,1100, Inf)
labels4 = c(6,  5, 4.5,4, 3.5, 3, 2.5, 2, 1.5, 1, 0.5, 0)
breaks5 = c(0,50,125,200,275,350,425,500,575,650,725,800, Inf)
labels5 = c(7, 6.5 , 6, 5.5, 5, 4.5,4, 3.5, 3, 2.5, 2, 1.5)
breaks6 = c(0,5,25,50,100,150,200,250,300,350,400,450, Inf)
labels6 = c(8, 7.5,7, 6.5, 6, 5.5, 5, 4.5, 4, 3.5, 3, 2.5)
breaks7 = c(0, 75, 100, 125,150,175,200,225,250, Inf)
#breaks7 = c(-Inf,250,225,200,175,150,125,100,75,-1)
#labels7 = c('4', '4.5', '5', '5.5', '6', '6.5', '7', '7.5', '8')
labels7 = c(8, 7.5, 7, 6.5, 6, 5.5, 5, 4.5, 4)

hier.env3 <- hier.env2 %>% mutate(aSMR = ifelse(MoistureRegime %in% SMR4, as.character(cut(CMD.site, breaks = breaks4, labels = labels4)),
                      ifelse (MoistureRegime %in% SMR5,as.character(cut(CMD.site, breaks = breaks5, labels = labels5)),
ifelse (MoistureRegime %in% SMR6, as.character(cut(CMD.site, breaks = breaks6, labels = labels6)),
ifelse (MoistureRegime %in% SMR7, as.character(cut(CMD.site, breaks = breaks7, labels = labels7)), 999)))))


edatopic.sum <- hier.env3 %>% group_by(Assoc) %>% count(aSMR,NutrientRegime)

require(summarytools)
xx <- hier.env3 %>% group_by(Assoc) %>% descr()


```

##Internal Metrics of Homogeneity of site series - Vegetation
Number of plots
Similarity between plots
Outliers

